-- Ampliación biblioteca Gen-Z (2026-06-30). 40 prendas: 20 hombre + 20 mujer, con
-- siluetas Gen-Z (oversized/baggy/cargo/chunky/corset/slip/platform) manteniendo la
-- paleta neutra del catálogo. Flat-lays en public/archetypes/. onboarding_subset=false.
-- Idempotente (on conflict slug do nothing).
insert into public.archetypes (slug, name, category, segment, attrs, image_path, sort_order, onboarding_subset) values
  ('genz-tee-oversized-blanca', 'Camiseta oversized blanca', 'top', 'hombre', '{"color":"blanco","color_hex":"#F2F1EE","temporada":"calor","formalidad":"casual"}', '/archetypes/genz-tee-oversized-blanca.png', 264, false),
  ('genz-hoodie-oversized-gris', 'Hoodie oversized gris', 'top', 'hombre', '{"color":"gris","color_hex":"#8A8A8A","temporada":"templado","formalidad":"casual"}', '/archetypes/genz-hoodie-oversized-gris.png', 265, false),
  ('genz-crewneck-crema-h', 'Sudadera crewneck crema', 'top', 'hombre', '{"color":"crema","color_hex":"#E6DFD2","temporada":"templado","formalidad":"casual"}', '/archetypes/genz-crewneck-crema-h.png', 266, false),
  ('genz-tee-grafica-h', 'Playera gráfica blanca', 'top', 'hombre', '{"color":"blanco","color_hex":"#F2F1EE","temporada":"calor","formalidad":"casual"}', '/archetypes/genz-tee-grafica-h.png', 267, false),
  ('genz-rayas-oversized-h', 'Playera de rayas oversized', 'top', 'hombre', '{"color":"marino","color_hex":"#2A3B57","temporada":"templado","formalidad":"casual"}', '/archetypes/genz-rayas-oversized-h.png', 268, false),
  ('genz-overshirt-cafe', 'Overshirt café', 'abrigo', 'hombre', '{"color":"café","color_hex":"#6E5844","temporada":"templado","formalidad":"casual"}', '/archetypes/genz-overshirt-cafe.png', 269, false),
  ('genz-jeans-baggy-claros-h', 'Jeans baggy claros', 'bottom', 'hombre', '{"color":"azul claro","color_hex":"#8FA6C4","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-jeans-baggy-claros-h.png', 270, false),
  ('genz-cargo-negros-h', 'Pantalón cargo negro', 'bottom', 'hombre', '{"color":"negro","color_hex":"#23242A","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-cargo-negros-h.png', 271, false),
  ('genz-wide-leg-gris-h', 'Pantalón wide-leg gris', 'bottom', 'hombre', '{"color":"gris","color_hex":"#6D6E72","temporada":"templado","formalidad":"formal-casual"}', '/archetypes/genz-wide-leg-gris-h.png', 272, false),
  ('genz-jeans-negros-rectos-h', 'Jeans negros rectos', 'bottom', 'hombre', '{"color":"negro","color_hex":"#1F1F22","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-jeans-negros-rectos-h.png', 273, false),
  ('genz-shorts-cargo-beige-h', 'Shorts cargo beige', 'bottom', 'hombre', '{"color":"beige","color_hex":"#C9BCA3","temporada":"calor","formalidad":"casual"}', '/archetypes/genz-shorts-cargo-beige-h.png', 274, false),
  ('genz-bomber-negro-h', 'Bomber negro', 'abrigo', 'hombre', '{"color":"negro","color_hex":"#1E1E22","temporada":"templado","formalidad":"formal-casual"}', '/archetypes/genz-bomber-negro-h.png', 275, false),
  ('genz-puffer-vest-negro-h', 'Chaleco acolchado negro', 'abrigo', 'hombre', '{"color":"negro","color_hex":"#22232A","temporada":"frio","formalidad":"casual"}', '/archetypes/genz-puffer-vest-negro-h.png', 276, false),
  ('genz-varsity-h', 'Chamarra varsity', 'abrigo', 'hombre', '{"color":"crema","color_hex":"#E4DCCB","temporada":"templado","formalidad":"casual"}', '/archetypes/genz-varsity-h.png', 277, false),
  ('genz-denim-oversized-h', 'Chamarra denim oversized', 'abrigo', 'hombre', '{"color":"azul","color_hex":"#6E86A6","temporada":"templado","formalidad":"casual"}', '/archetypes/genz-denim-oversized-h.png', 278, false),
  ('genz-tenis-chunky-h', 'Tenis chunky blancos', 'calzado', 'hombre', '{"color":"blanco","color_hex":"#EFEFEC","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-tenis-chunky-h.png', 279, false),
  ('genz-tenis-samba-h', 'Tenis retro', 'calzado', 'hombre', '{"color":"blanco","color_hex":"#ECEAE4","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-tenis-samba-h.png', 280, false),
  ('genz-skate-lona-negros-h', 'Tenis skate negros', 'calzado', 'hombre', '{"color":"negro","color_hex":"#26262A","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-skate-lona-negros-h.png', 281, false),
  ('genz-beanie-negro-h', 'Gorro beanie negro', 'accesorio', 'hombre', '{"color":"negro","color_hex":"#1C1C1F","temporada":"frio","formalidad":"casual"}', '/archetypes/genz-beanie-negro-h.png', 282, false),
  ('genz-sling-bag-negra-h', 'Bolsa crossbody negra', 'accesorio', 'hombre', '{"color":"negro","color_hex":"#202024","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-sling-bag-negra-h.png', 283, false),
  ('genz-baby-tee-blanca-m', 'Baby tee blanca', 'top', 'mujer', '{"color":"blanco","color_hex":"#F2F1EE","temporada":"calor","formalidad":"casual"}', '/archetypes/genz-baby-tee-blanca-m.png', 284, false),
  ('genz-corset-top-blanco-m', 'Corset top blanco', 'top', 'mujer', '{"color":"blanco","color_hex":"#EFEDE7","temporada":"calor","formalidad":"formal-casual"}', '/archetypes/genz-corset-top-blanco-m.png', 285, false),
  ('genz-halter-negro-m', 'Top halter negro', 'top', 'mujer', '{"color":"negro","color_hex":"#201F23","temporada":"calor","formalidad":"formal-casual"}', '/archetypes/genz-halter-negro-m.png', 286, false),
  ('genz-knit-vest-crema-m', 'Chaleco de punto crema', 'top', 'mujer', '{"color":"crema","color_hex":"#E7E0D2","temporada":"templado","formalidad":"casual"}', '/archetypes/genz-knit-vest-crema-m.png', 287, false),
  ('genz-sudadera-oversized-gris-m', 'Sudadera oversized gris', 'top', 'mujer', '{"color":"gris","color_hex":"#8C8C8C","temporada":"templado","formalidad":"casual"}', '/archetypes/genz-sudadera-oversized-gris-m.png', 288, false),
  ('genz-grafica-oversized-m', 'Playera gráfica oversized', 'top', 'mujer', '{"color":"blanco","color_hex":"#F1F0ED","temporada":"calor","formalidad":"casual"}', '/archetypes/genz-grafica-oversized-m.png', 289, false),
  ('genz-jeans-baggy-alto-m', 'Jeans baggy tiro alto', 'bottom', 'mujer', '{"color":"azul medio","color_hex":"#5E79A0","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-jeans-baggy-alto-m.png', 290, false),
  ('genz-falda-cargo-mini-m', 'Falda cargo mini oliva', 'bottom', 'mujer', '{"color":"oliva","color_hex":"#5C5F44","temporada":"calor","formalidad":"casual"}', '/archetypes/genz-falda-cargo-mini-m.png', 291, false),
  ('genz-wide-leg-negro-m', 'Pantalón wide-leg negro', 'bottom', 'mujer', '{"color":"negro","color_hex":"#212127","temporada":"templado","formalidad":"formal-casual"}', '/archetypes/genz-wide-leg-negro-m.png', 292, false),
  ('genz-falda-plisada-tenis-m', 'Falda plisada tipo tenis', 'bottom', 'mujer', '{"color":"negro","color_hex":"#232326","temporada":"templado","formalidad":"casual"}', '/archetypes/genz-falda-plisada-tenis-m.png', 293, false),
  ('genz-jeans-flare-m', 'Jeans acampanados', 'bottom', 'mujer', '{"color":"azul","color_hex":"#6B84A8","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-jeans-flare-m.png', 294, false),
  ('genz-leggings-negros-m', 'Leggings negros', 'bottom', 'mujer', '{"color":"negro","color_hex":"#1F1F22","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-leggings-negros-m.png', 295, false),
  ('genz-bomber-crema-m', 'Bomber crema', 'abrigo', 'mujer', '{"color":"crema","color_hex":"#E5DDCC","temporada":"templado","formalidad":"formal-casual"}', '/archetypes/genz-bomber-crema-m.png', 296, false),
  ('genz-cardigan-oversized-beige-m', 'Cardigan oversized beige', 'abrigo', 'mujer', '{"color":"beige","color_hex":"#D8CBB4","temporada":"templado","formalidad":"casual"}', '/archetypes/genz-cardigan-oversized-beige-m.png', 297, false),
  ('genz-trench-oversized-camel-m', 'Trench oversized camel', 'abrigo', 'mujer', '{"color":"camel","color_hex":"#B7986A","temporada":"templado","formalidad":"formal-casual"}', '/archetypes/genz-trench-oversized-camel-m.png', 298, false),
  ('genz-slip-dress-negro-m', 'Slip dress satinado negro', 'vestido', 'mujer', '{"color":"negro","color_hex":"#1E1D21","temporada":"calor","formalidad":"formal-casual"}', '/archetypes/genz-slip-dress-negro-m.png', 299, false),
  ('genz-tenis-chunky-m', 'Tenis chunky blancos', 'calzado', 'mujer', '{"color":"blanco","color_hex":"#EFEFEC","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-tenis-chunky-m.png', 300, false),
  ('genz-tenis-samba-m', 'Tenis retro', 'calzado', 'mujer', '{"color":"blanco","color_hex":"#ECEAE4","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-tenis-samba-m.png', 301, false),
  ('genz-mary-jane-platform-m', 'Mary Jane platform negras', 'calzado', 'mujer', '{"color":"negro","color_hex":"#242428","temporada":"todo-el-año","formalidad":"formal-casual"}', '/archetypes/genz-mary-jane-platform-m.png', 302, false),
  ('genz-hobo-bag-cafe-m', 'Bolsa hobo café', 'accesorio', 'mujer', '{"color":"café","color_hex":"#6F5A45","temporada":"todo-el-año","formalidad":"casual"}', '/archetypes/genz-hobo-bag-cafe-m.png', 303, false)
on conflict (slug) do nothing;
